[18/Oct/2022 11:53:57,530] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/MainPartSiteDGU/json_logger_custom.py changed, reloading. autoreload.py INFO
[18/Oct/2022 11:57:07,491] Watching for file changes with StatReloader autoreload.py INFO
[18/Oct/2022 11:57:13] [m"GET /list_students/ HTTP/1.1" 200 16980[0m basehttp.py INFO
[18/Oct/2022 11:58:18,372] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/MainPartSiteDGU/json_logger_custom.py changed, reloading. autoreload.py INFO
[18/Oct/2022 11:58:18,766] Watching for file changes with StatReloader autoreload.py INFO
[18/Oct/2022 11:58:23] [m"GET /list_students/ HTTP/1.1" 200 16980[0m basehttp.py INFO
[18/Oct/2022 11:59:10,365] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/MainPartSiteDGU/json_logger_custom.py changed, reloading. autoreload.py INFO
[18/Oct/2022 11:59:10,781] Watching for file changes with StatReloader autoreload.py INFO
[18/Oct/2022 11:59:15] [m"GET /list_students/ HTTP/1.1" 200 16980[0m basehttp.py INFO
[18/Oct/2022 11:59:54,301] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/MainPartSiteDGU/json_logger_custom.py changed, reloading. autoreload.py INFO
[18/Oct/2022 11:59:55,132] Watching for file changes with StatReloader autoreload.py INFO
[18/Oct/2022 11:59:58] [m"GET /list_students/ HTTP/1.1" 200 16980[0m basehttp.py INFO
[18/Oct/2022 12:00:06,931] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/MainPartSiteDGU/json_logger_custom.py changed, reloading. autoreload.py INFO
[18/Oct/2022 12:00:07,426] Watching for file changes with StatReloader autoreload.py INFO
[18/Oct/2022 12:00:08] [m"GET /list_students/ HTTP/1.1" 200 16980[0m basehttp.py INFO
[18/Oct/2022 12:00:28,325] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/MainPartSiteDGU/json_logger_custom.py changed, reloading. autoreload.py INFO
[18/Oct/2022 12:00:28,836] Watching for file changes with StatReloader autoreload.py INFO
[18/Oct/2022 12:00:29] [m"GET /list_students/ HTTP/1.1" 200 16980[0m basehttp.py INFO
[18/Oct/2022 12:01:06,342] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/MainPartSiteDGU/settings.py changed, reloading. autoreload.py INFO
[18/Oct/2022 12:25:04,552] Watching for file changes with StatReloader autoreload.py INFO
[18/Oct/2022 12:25:16,034] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/MainPartSiteDGU/settings.py changed, reloading. autoreload.py INFO
[18/Oct/2022 12:25:34,941] Watching for file changes with StatReloader autoreload.py INFO
[18/Oct/2022 12:29:35,390] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/MainPartSiteDGU/json_logger_custom.py changed, reloading. autoreload.py INFO
[18/Oct/2022 12:30:33,919] Watching for file changes with StatReloader autoreload.py INFO
[18/Oct/2022 12:30:36] [m"GET /list_students/ HTTP/1.1" 200 16980[0m basehttp.py INFO
[18/Oct/2022 12:30:39] [m"GET /list_students/ HTTP/1.1" 200 16978[0m basehttp.py INFO
[18/Oct/2022 12:31:06,186] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/MainPartSiteDGU/json_logger_custom.py changed, reloading. autoreload.py INFO
[18/Oct/2022 12:31:07,267] Watching for file changes with StatReloader autoreload.py INFO
[18/Oct/2022 12:31:07] [m"GET /list_students/ HTTP/1.1" 200 16980[0m basehttp.py INFO
[18/Oct/2022 12:35:41,280] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/MainPartSiteDGU/json_logger_custom.py changed, reloading. autoreload.py INFO
[18/Oct/2022 12:35:42,223] Watching for file changes with StatReloader autoreload.py INFO
[18/Oct/2022 12:35:43] [m"GET /list_students/ HTTP/1.1" 200 16980[0m basehttp.py INFO
[18/Oct/2022 12:40:43,571] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/MainPartSiteDGU/json_logger_custom.py changed, reloading. autoreload.py INFO
[18/Oct/2022 12:40:45,376] Watching for file changes with StatReloader autoreload.py INFO
[18/Oct/2022 12:40:47] [m"GET /list_students/ HTTP/1.1" 200 16980[0m basehttp.py INFO
[18/Oct/2022 12:41:23,772] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/MainPartSiteDGU/json_logger_custom.py changed, reloading. autoreload.py INFO
[18/Oct/2022 12:41:24,275] Watching for file changes with StatReloader autoreload.py INFO
[18/Oct/2022 12:42:02,686] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/MainPartSiteDGU/json_logger_custom.py changed, reloading. autoreload.py INFO
[18/Oct/2022 12:42:03,810] Watching for file changes with StatReloader autoreload.py INFO
[18/Oct/2022 12:42:05] [m"GET /list_students/ HTTP/1.1" 200 16980[0m basehttp.py INFO
[18/Oct/2022 12:42:14] [m"GET /list_students/ HTTP/1.1" 200 16978[0m basehttp.py INFO
[18/Oct/2022 12:42:31,793] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/MainPartSiteDGU/json_logger_custom.py changed, reloading. autoreload.py INFO
[18/Oct/2022 12:42:32,639] Watching for file changes with StatReloader autoreload.py INFO
[18/Oct/2022 12:42:58,471] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/MainPartSiteDGU/json_logger_custom.py changed, reloading. autoreload.py INFO
[18/Oct/2022 12:42:58,825] Watching for file changes with StatReloader autoreload.py INFO
[18/Oct/2022 12:43:03] [m"GET /list_students/ HTTP/1.1" 200 16980[0m basehttp.py INFO
[18/Oct/2022 12:46:53,227] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/MainPartSiteDGU/json_logger_custom.py changed, reloading. autoreload.py INFO
[18/Oct/2022 12:46:54,877] Watching for file changes with StatReloader autoreload.py INFO
[18/Oct/2022 12:46:57] [m"GET /list_students/ HTTP/1.1" 200 16980[0m basehttp.py INFO
[18/Oct/2022 12:52:34] [m"GET /list_events/ HTTP/1.1" 200 17172[0m basehttp.py INFO
[18/Oct/2022 12:52:34] [m"GET /media/Events/2022/10.17/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA_%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0_2022-08-16_%D0%B2_14.56.39.png HTTP/1.1" 200 282542[0m basehttp.py INFO
[18/Oct/2022 12:52:34] [m"GET /media/Events/2022/10.13/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA_%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0_2022-08-16_%D0%B2_14.56.56_WAty4Ft.png HTTP/1.1" 200 288574[0m basehttp.py INFO
[18/Oct/2022 12:52:34] [m"GET /media/Events/2022/10.13/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA_%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0_2022-08-16_%D0%B2_14.56.56_Cnp9lwP.png HTTP/1.1" 200 288574[0m basehttp.py INFO
[18/Oct/2022 12:52:34] [m"GET /media/Events/2022/10.13/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA_%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0_2022-08-16_%D0%B2_14.56.56_hYLxXrv.png HTTP/1.1" 200 288574[0m basehttp.py INFO
[18/Oct/2022 12:52:36] [m"GET /create_events/ HTTP/1.1" 200 15319[0m basehttp.py INFO
[19/Oct/2022 11:44:26,850] Watching for file changes with StatReloader autoreload.py INFO
[19/Oct/2022 11:44:48] [m"GET /auth/ HTTP/1.1" 200 16274[0m basehttp.py INFO
[19/Oct/2022 11:44:48] [m"GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385[0m basehttp.py INFO
[19/Oct/2022 11:44:48] [m"GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817[0m basehttp.py INFO
[19/Oct/2022 11:44:48] [m"GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719[0m basehttp.py INFO
[19/Oct/2022 11:44:48] [m"GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457[0m basehttp.py INFO
[19/Oct/2022 11:44:48] [m"GET /static/rest_framework/css/default.css HTTP/1.1" 200 1152[0m basehttp.py INFO
[19/Oct/2022 11:44:48] [m"GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268[0m basehttp.py INFO
[19/Oct/2022 11:44:48] [m"GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597[0m basehttp.py INFO
[19/Oct/2022 11:44:48] [m"GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 200 89476[0m basehttp.py INFO
[19/Oct/2022 11:44:48] [m"GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680[0m basehttp.py INFO
[19/Oct/2022 11:44:48] [m"GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632[0m basehttp.py INFO
[19/Oct/2022 11:44:48] [m"GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458[0m basehttp.py INFO
[19/Oct/2022 11:44:57] [m"GET /auth/users/ HTTP/1.1" 200 22251[0m basehttp.py INFO
[19/Oct/2022 11:45:56,039] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/MainPartSiteDGU/urls.py changed, reloading. autoreload.py INFO
[19/Oct/2022 11:45:57,302] Watching for file changes with StatReloader autoreload.py INFO
[19/Oct/2022 11:46:00,974] [33mNot Found: /drf_auth[0m log.py WARNING
[19/Oct/2022 11:46:00] [33m"GET /drf_auth HTTP/1.1" 404 15777[0m basehttp.py WARNING
[19/Oct/2022 11:46:03,284] [33mNot Found: /drf_auth/[0m log.py WARNING
[19/Oct/2022 11:46:03] [33m"GET /drf_auth/ HTTP/1.1" 404 16026[0m basehttp.py WARNING
[19/Oct/2022 11:46:12] [m"GET /drf_auth/login/ HTTP/1.1" 200 13676[0m basehttp.py INFO
[19/Oct/2022 11:46:16] [32m"POST /drf_auth/login/ HTTP/1.1" 302 0[0m basehttp.py INFO
[19/Oct/2022 11:46:16,819] [33mNot Found: /accounts/profile/[0m log.py WARNING
[19/Oct/2022 11:46:16] [33m"GET /accounts/profile/ HTTP/1.1" 404 15813[0m basehttp.py WARNING
[19/Oct/2022 11:47:09,642] [33mNot Found: /accounts/profile/list_students[0m log.py WARNING
[19/Oct/2022 11:47:09] [33m"GET /accounts/profile/list_students HTTP/1.1" 404 15865[0m basehttp.py WARNING
[19/Oct/2022 11:47:16,026] [33mNot Found: /accounts/list_students/[0m log.py WARNING
[19/Oct/2022 11:47:16] [33m"GET /accounts/list_students/ HTTP/1.1" 404 15837[0m basehttp.py WARNING
[19/Oct/2022 11:47:37,760] [33mNot Found: /drf_auth/[0m log.py WARNING
[19/Oct/2022 11:47:37] [33m"GET /drf_auth/ HTTP/1.1" 404 16026[0m basehttp.py WARNING
[19/Oct/2022 11:49:20,996] [33mNot Found: /drf_auth/[0m log.py WARNING
[19/Oct/2022 11:49:20] [33m"POST /drf_auth/ HTTP/1.1" 404 16027[0m basehttp.py WARNING
[19/Oct/2022 11:49:52,198] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/MainPartSiteDGU/settings.py changed, reloading. autoreload.py INFO
[19/Oct/2022 11:50:24,843] Watching for file changes with StatReloader autoreload.py INFO
[19/Oct/2022 11:50:39,731] [31;1mForbidden (CSRF cookie not set.): /drf_auth/login/[0m log.py WARNING
[19/Oct/2022 11:50:39] [31;1m"POST /drf_auth/login/ HTTP/1.1" 403 14252[0m basehttp.py WARNING
[19/Oct/2022 11:50:56] [m"GET /admin/Students/infostudent/ HTTP/1.1" 200 21121[0m basehttp.py INFO
[19/Oct/2022 11:50:57] [m"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2616[0m basehttp.py INFO
[19/Oct/2022 11:50:57] [m"GET /static/admin/css/changelists.css HTTP/1.1" 200 6932[0m basehttp.py INFO
[19/Oct/2022 11:50:57] [m"GET /static/admin/css/responsive.css HTTP/1.1" 200 18545[0m basehttp.py INFO
[19/Oct/2022 11:50:57] [m"GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347[0m basehttp.py INFO
[19/Oct/2022 11:50:57] [m"GET /static/admin/js/core.js HTTP/1.1" 200 5698[0m basehttp.py INFO
[19/Oct/2022 11:50:57] [m"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 288580[0m basehttp.py INFO
[19/Oct/2022 11:50:57] [m"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 5984[0m basehttp.py INFO
[19/Oct/2022 11:50:57] [m"GET /static/admin/js/actions.js HTTP/1.1" 200 7872[0m basehttp.py INFO
[19/Oct/2022 11:50:57] [m"GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531[0m basehttp.py INFO
[19/Oct/2022 11:50:57] [m"GET /static/admin/js/urlify.js HTTP/1.1" 200 7902[0m basehttp.py INFO
[19/Oct/2022 11:50:57] [m"GET /admin/jsi18n/ HTTP/1.1" 200 15618[0m basehttp.py INFO
[19/Oct/2022 11:50:57] [m"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 232381[0m basehttp.py INFO
[19/Oct/2022 11:50:57] [m"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3401[0m basehttp.py INFO
[19/Oct/2022 11:50:57] [m"GET /static/admin/css/base.css HTTP/1.1" 200 19513[0m basehttp.py INFO
[19/Oct/2022 11:50:57] [m"GET /static/admin/css/fonts.css HTTP/1.1" 200 423[0m basehttp.py INFO
[19/Oct/2022 11:50:57] [m"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331[0m basehttp.py INFO
[19/Oct/2022 11:50:57] [m"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331[0m basehttp.py INFO
[19/Oct/2022 11:50:58] [m"GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692[0m basehttp.py INFO
[19/Oct/2022 11:50:58] [m"GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876[0m basehttp.py INFO
[19/Oct/2022 11:50:58] [m"GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184[0m basehttp.py INFO
[19/Oct/2022 11:50:59] [m"GET /admin/Students/infostudent/ HTTP/1.1" 200 21120[0m basehttp.py INFO
[19/Oct/2022 11:51:00] [m"GET /admin/jsi18n/ HTTP/1.1" 200 15618[0m basehttp.py INFO
[19/Oct/2022 11:51:04] [m"GET /admin/logout/ HTTP/1.1" 200 12579[0m basehttp.py INFO
[19/Oct/2022 11:51:06,729] [33mNot Found: /drf_auth/[0m log.py WARNING
[19/Oct/2022 11:51:06] [33m"GET /drf_auth/ HTTP/1.1" 404 16026[0m basehttp.py WARNING
[19/Oct/2022 11:51:14] [m"GET /drf_auth/login/ HTTP/1.1" 200 13676[0m basehttp.py INFO
[19/Oct/2022 11:51:21,387] [33mNot Found: /drf_auth/loout/[0m log.py WARNING
[19/Oct/2022 11:51:21] [33m"GET /drf_auth/loout/ HTTP/1.1" 404 16050[0m basehttp.py WARNING
[19/Oct/2022 11:51:27,268] [33mNot Found: /drf_auth/logut/[0m log.py WARNING
[19/Oct/2022 11:51:27] [33m"GET /drf_auth/logut/ HTTP/1.1" 404 16050[0m basehttp.py WARNING
[19/Oct/2022 11:51:41] [m"GET /drf_auth/logout/ HTTP/1.1" 200 12418[0m basehttp.py INFO
[19/Oct/2022 11:51:48] [m"GET /drf_auth/login/ HTTP/1.1" 200 13676[0m basehttp.py INFO
[19/Oct/2022 11:51:53] [32m"POST /drf_auth/login/ HTTP/1.1" 302 0[0m basehttp.py INFO
[19/Oct/2022 11:51:53,079] [33mNot Found: /accounts/profile/[0m log.py WARNING
[19/Oct/2022 11:51:53] [33m"GET /accounts/profile/ HTTP/1.1" 404 15813[0m basehttp.py WARNING
[19/Oct/2022 11:51:58] [m"GET /admin/logout/ HTTP/1.1" 200 12579[0m basehttp.py INFO
[19/Oct/2022 11:52:02] [32m"GET /admin/ HTTP/1.1" 302 0[0m basehttp.py INFO
[19/Oct/2022 11:52:02] [m"GET /admin/login/?next=/admin/ HTTP/1.1" 200 13252[0m basehttp.py INFO
[19/Oct/2022 11:52:02] [36m"GET /static/admin/css/login.css HTTP/1.1" 304 0[0m basehttp.py INFO
[19/Oct/2022 11:52:12] [m"GET /drf_auth/login/ HTTP/1.1" 200 13676[0m basehttp.py INFO
[19/Oct/2022 11:52:18] [32m"POST /drf_auth/login/ HTTP/1.1" 302 0[0m basehttp.py INFO
[19/Oct/2022 11:52:18,106] [33mNot Found: /accounts/profile/[0m log.py WARNING
[19/Oct/2022 11:52:18] [33m"GET /accounts/profile/ HTTP/1.1" 404 15813[0m basehttp.py WARNING
[19/Oct/2022 11:52:23] [32m"GET /admin/login/?next=/admin/ HTTP/1.1" 302 0[0m basehttp.py INFO
[19/Oct/2022 11:52:23] [m"GET /admin/ HTTP/1.1" 200 19820[0m basehttp.py INFO
[19/Oct/2022 11:52:24] [m"GET /static/admin/css/dashboard.css HTTP/1.1" 200 380[0m basehttp.py INFO
[19/Oct/2022 11:52:24] [m"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380[0m basehttp.py INFO
[19/Oct/2022 11:52:24] [m"GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 200 392[0m basehttp.py INFO
[19/Oct/2022 11:52:46] [m"GET /auth/users/ HTTP/1.1" 200 22509[0m basehttp.py INFO
[19/Oct/2022 11:53:03,377] [31;1mUnauthorized: /auth/users/[0m log.py WARNING
[19/Oct/2022 11:53:03] [31;1m"GET /auth/users/ HTTP/1.1" 401 82[0m basehttp.py WARNING
[19/Oct/2022 11:53:57,863] [31;1mMethod Not Allowed: /auth/jwt/create/[0m log.py WARNING
[19/Oct/2022 11:53:57] [31;1m"GET /auth/jwt/create/ HTTP/1.1" 405 54[0m basehttp.py WARNING
[19/Oct/2022 11:54:03,137] [31;1mBad Request: /auth/jwt/create/[0m log.py WARNING
[19/Oct/2022 11:54:03] [31;1m"POST /auth/jwt/create/ HTTP/1.1" 400 101[0m basehttp.py WARNING
[19/Oct/2022 11:54:22] [m"POST /auth/jwt/create/ HTTP/1.1" 200 438[0m basehttp.py INFO
[19/Oct/2022 11:55:21,893] [31;1mUnauthorized: /auth/users/[0m log.py WARNING
[19/Oct/2022 11:55:21] [31;1m"GET /auth/users/ HTTP/1.1" 401 82[0m basehttp.py WARNING
[19/Oct/2022 11:55:49,590] [31;1mUnauthorized: /auth/users/[0m log.py WARNING
[19/Oct/2022 11:55:49] [31;1m"GET /auth/users/ HTTP/1.1" 401 176[0m basehttp.py WARNING
[19/Oct/2022 11:56:00] [m"POST /auth/jwt/create/ HTTP/1.1" 200 438[0m basehttp.py INFO
[19/Oct/2022 11:56:11,112] [31;1mUnauthorized: /auth/users/[0m log.py WARNING
[19/Oct/2022 11:56:11] [31;1m"GET /auth/users/ HTTP/1.1" 401 176[0m basehttp.py WARNING
[19/Oct/2022 11:56:52,187] [31;1mBad Request: /auth/jwt/verify/[0m log.py WARNING
[19/Oct/2022 11:56:52] [31;1m"POST /auth/jwt/verify/ HTTP/1.1" 400 48[0m basehttp.py WARNING
[19/Oct/2022 11:57:03] [m"POST /auth/jwt/verify/ HTTP/1.1" 200 2[0m basehttp.py INFO
[19/Oct/2022 11:57:07] [m"POST /auth/jwt/verify/ HTTP/1.1" 200 2[0m basehttp.py INFO
[19/Oct/2022 11:57:17,139] [31;1mMethod Not Allowed: /auth/jwt/verify/[0m log.py WARNING
[19/Oct/2022 11:57:17] [31;1m"GET /auth/jwt/verify/ HTTP/1.1" 405 18487[0m basehttp.py WARNING
[19/Oct/2022 11:57:23] [m"POST /auth/jwt/verify/ HTTP/1.1" 200 18383[0m basehttp.py INFO
[19/Oct/2022 11:57:32] [m"GET /admin/ HTTP/1.1" 200 19819[0m basehttp.py INFO
[19/Oct/2022 11:57:37] [m"POST /auth/jwt/verify/ HTTP/1.1" 200 18383[0m basehttp.py INFO
[19/Oct/2022 11:57:55,370] [31;1mMethod Not Allowed: /auth/jwt/create/[0m log.py WARNING
[19/Oct/2022 11:57:55] [31;1m"GET /auth/jwt/create/ HTTP/1.1" 405 18819[0m basehttp.py WARNING
[19/Oct/2022 11:57:59] [m"POST /auth/jwt/create/ HTTP/1.1" 200 19202[0m basehttp.py INFO
[19/Oct/2022 11:58:05,930] [31;1mMethod Not Allowed: /auth/jwt/create/[0m log.py WARNING
[19/Oct/2022 11:58:05] [31;1m"GET /auth/jwt/create/ HTTP/1.1" 405 18819[0m basehttp.py WARNING
[19/Oct/2022 11:58:10] [m"POST /auth/jwt/verify/ HTTP/1.1" 200 18383[0m basehttp.py INFO
[19/Oct/2022 14:44:31] [m"GET /__debug__/render_panel/?store_id=529cdc1e89b24ccf90d2fa993cb9570a&panel_id=SQLPanel HTTP/1.1" 200 531[0m basehttp.py INFO
[19/Oct/2022 14:44:35] [m"GET /create_events/ HTTP/1.1" 200 15319[0m basehttp.py INFO
[19/Oct/2022 14:44:36] [36m"GET /static/css/style.css HTTP/1.1" 304 0[0m basehttp.py INFO
[19/Oct/2022 14:44:36] [36m"GET /static/icon/logo.png HTTP/1.1" 304 0[0m basehttp.py INFO
[19/Oct/2022 14:44:39] [m"GET /create_events/ HTTP/1.1" 200 15319[0m basehttp.py INFO
[19/Oct/2022 14:44:41] [m"GET /create_events/ HTTP/1.1" 200 15319[0m basehttp.py INFO
[19/Oct/2022 14:44:41] [m"GET /create_events/ HTTP/1.1" 200 15319[0m basehttp.py INFO
[19/Oct/2022 14:44:43] [m"GET /list_events/ HTTP/1.1" 200 17174[0m basehttp.py INFO
[19/Oct/2022 14:44:43] [m"GET /media/Events/2022/10.13/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA_%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0_2022-08-16_%D0%B2_14.56.56_Cnp9lwP.png HTTP/1.1" 200 288574[0m basehttp.py INFO
[19/Oct/2022 14:44:43] [m"GET /media/Events/2022/10.13/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA_%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0_2022-08-16_%D0%B2_14.56.56_hYLxXrv.png HTTP/1.1" 200 288574[0m basehttp.py INFO
[19/Oct/2022 14:44:43] [m"GET /media/Events/2022/10.13/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA_%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0_2022-08-16_%D0%B2_14.56.56_WAty4Ft.png HTTP/1.1" 200 288574[0m basehttp.py INFO
[19/Oct/2022 14:44:43] [m"GET /media/Events/2022/10.17/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA_%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0_2022-08-16_%D0%B2_14.56.39.png HTTP/1.1" 200 282542[0m basehttp.py INFO
[19/Oct/2022 14:44:44] [m"GET /list_students/ HTTP/1.1" 200 16980[0m basehttp.py INFO
[19/Oct/2022 14:44:45] [m"GET /media/photo/2022/10.17/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA_%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0_2022-08-12_%D0%B2_16.29.39.png HTTP/1.1" 200 6052[0m basehttp.py INFO
[19/Oct/2022 14:44:45] [m"GET /media/photo/2022/10.17/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA_%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0_2022-08-16_%D0%B2_14.56.39.png HTTP/1.1" 200 282542[0m basehttp.py INFO
[19/Oct/2022 14:44:45] [m"GET /media/photo/2022/10.17/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA_%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0_2022-08-16_%D0%B2_14.56.56.png HTTP/1.1" 200 288574[0m basehttp.py INFO
[19/Oct/2022 14:44:45] [m"GET /media/photo/2022/10.17/LWScreenShot_2022-09-02_at_17.30.40.png HTTP/1.1" 200 23927349[0m basehttp.py INFO
[19/Oct/2022 14:44:46] [m"GET /type_reg_student/ HTTP/1.1" 200 13860[0m basehttp.py INFO
[19/Oct/2022 14:44:48] [m"GET /list_events/ HTTP/1.1" 200 17174[0m basehttp.py INFO
[19/Oct/2022 14:44:54,912] [31;1mMethod Not Allowed: /auth/jwt/verify/[0m log.py WARNING
[19/Oct/2022 14:44:54] [31;1m"GET /auth/jwt/verify/ HTTP/1.1" 405 18489[0m basehttp.py WARNING
[19/Oct/2022 14:44:57] [m"GET /drf_auth/login/?next=/auth/jwt/verify/ HTTP/1.1" 200 13716[0m basehttp.py INFO
[19/Oct/2022 14:45:03] [m"GET /admin/ HTTP/1.1" 200 19821[0m basehttp.py INFO
[19/Oct/2022 14:45:08] [32m"POST /drf_auth/login/ HTTP/1.1" 302 0[0m basehttp.py INFO
[19/Oct/2022 14:45:08,227] [31;1mMethod Not Allowed: /auth/jwt/verify/[0m log.py WARNING
[19/Oct/2022 14:45:08] [31;1m"GET /auth/jwt/verify/ HTTP/1.1" 405 18489[0m basehttp.py WARNING
[19/Oct/2022 14:45:12] [m"GET /drf_auth/login/?next=/auth/jwt/verify/ HTTP/1.1" 200 13716[0m basehttp.py INFO
[19/Oct/2022 14:45:15] [32m"POST /drf_auth/login/ HTTP/1.1" 302 0[0m basehttp.py INFO
[19/Oct/2022 14:45:15,996] [31;1mMethod Not Allowed: /auth/jwt/verify/[0m log.py WARNING
[19/Oct/2022 14:45:15] [31;1m"GET /auth/jwt/verify/ HTTP/1.1" 405 18489[0m basehttp.py WARNING
[19/Oct/2022 14:45:34,906] [33mNot Found: /[0m log.py WARNING
[19/Oct/2022 14:45:34] [33m"GET / HTTP/1.1" 404 15729[0m basehttp.py WARNING
[19/Oct/2022 14:45:44,979] [33mNot Found: /drf_auth/[0m log.py WARNING
[19/Oct/2022 14:45:44] [33m"GET /drf_auth/ HTTP/1.1" 404 16028[0m basehttp.py WARNING
[19/Oct/2022 14:45:51] [m"GET /drf_auth/login/ HTTP/1.1" 200 13676[0m basehttp.py INFO
[19/Oct/2022 14:45:54] [32m"POST /drf_auth/login/ HTTP/1.1" 302 0[0m basehttp.py INFO
[19/Oct/2022 14:45:54,840] [33mNot Found: /accounts/profile/[0m log.py WARNING
[19/Oct/2022 14:45:54] [33m"GET /accounts/profile/ HTTP/1.1" 404 15815[0m basehttp.py WARNING
[19/Oct/2022 14:46:03] [m"GET /auth/ HTTP/1.1" 200 16526[0m basehttp.py INFO
[19/Oct/2022 14:46:10] [m"GET /auth/users/ HTTP/1.1" 200 22513[0m basehttp.py INFO
[19/Oct/2022 14:55:51,028] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/MainPartSiteDGU/urls.py changed, reloading. autoreload.py INFO
[19/Oct/2022 14:55:51,742] Watching for file changes with StatReloader autoreload.py INFO
[19/Oct/2022 14:56:30,914] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[19/Oct/2022 14:56:31,326] Watching for file changes with StatReloader autoreload.py INFO
[19/Oct/2022 14:56:48,958] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[19/Oct/2022 14:56:49,490] Watching for file changes with StatReloader autoreload.py INFO
[19/Oct/2022 14:59:48,669] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[19/Oct/2022 14:59:49,624] Watching for file changes with StatReloader autoreload.py INFO
[19/Oct/2022 15:00:04,630] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[19/Oct/2022 15:00:05,134] Watching for file changes with StatReloader autoreload.py INFO
[19/Oct/2022 15:09:45,843] Watching for file changes with StatReloader autoreload.py INFO
[19/Oct/2022 15:10:00,393] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[19/Oct/2022 15:10:00,879] Watching for file changes with StatReloader autoreload.py INFO
[19/Oct/2022 15:10:56,382] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[19/Oct/2022 15:10:56,806] Watching for file changes with StatReloader autoreload.py INFO
[19/Oct/2022 15:14:59,447] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[19/Oct/2022 15:14:59,931] Watching for file changes with StatReloader autoreload.py INFO
[20/Oct/2022 11:16:21,405] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[20/Oct/2022 11:16:22,138] Watching for file changes with StatReloader autoreload.py INFO
[20/Oct/2022 11:16:52,151] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/views.py changed, reloading. autoreload.py INFO
[20/Oct/2022 11:16:52,641] Watching for file changes with StatReloader autoreload.py INFO
[20/Oct/2022 11:18:57,938] [33mNot Found: /api/list_events/[0m log.py WARNING
[20/Oct/2022 11:18:57] [33m"GET /api/list_events/ HTTP/1.1" 404 15996[0m basehttp.py WARNING
[20/Oct/2022 11:18:58] [36m"GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 304 0[0m basehttp.py INFO
[20/Oct/2022 11:18:58] [36m"GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 304 0[0m basehttp.py INFO
[20/Oct/2022 11:18:58] [36m"GET /static/debug_toolbar/css/print.css HTTP/1.1" 304 0[0m basehttp.py INFO
[20/Oct/2022 11:18:58] [36m"GET /static/debug_toolbar/js/utils.js HTTP/1.1" 304 0[0m basehttp.py INFO
[20/Oct/2022 11:19:07,434] [33mNot Found: /[0m log.py WARNING
[20/Oct/2022 11:19:07] [33m"GET / HTTP/1.1" 404 15831[0m basehttp.py WARNING
[20/Oct/2022 11:19:16,143] [33mNot Found: /api/[0m log.py WARNING
[20/Oct/2022 11:19:16] [33m"GET /api/ HTTP/1.1" 404 15948[0m basehttp.py WARNING
[20/Oct/2022 11:19:23,196] [33mNot Found: /api/list_students.[0m log.py WARNING
[20/Oct/2022 11:19:23] [33m"GET /api/list_students. HTTP/1.1" 404 16004[0m basehttp.py WARNING
[20/Oct/2022 11:19:27] [m"GET /api/list_students/ HTTP/1.1" 200 21325[0m basehttp.py INFO
[20/Oct/2022 11:19:42,647] [33mNot Found: /[0m log.py WARNING
[20/Oct/2022 11:19:42] [33m"GET / HTTP/1.1" 404 15833[0m basehttp.py WARNING
[20/Oct/2022 11:19:46] [m"GET /list_students/ HTTP/1.1" 200 16988[0m basehttp.py INFO
[20/Oct/2022 11:19:46] [36m"GET /static/css/style.css HTTP/1.1" 304 0[0m basehttp.py INFO
[20/Oct/2022 11:19:47] [m"GET /static/icon/logo.png HTTP/1.1" 200 513410[0m basehttp.py INFO
[20/Oct/2022 11:19:47] [m"GET /media/photo/2022/10.17/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA_%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0_2022-08-16_%D0%B2_14.56.56.png HTTP/1.1" 200 288574[0m basehttp.py INFO
[20/Oct/2022 11:19:47] [m"GET /media/photo/2022/10.17/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA_%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0_2022-08-12_%D0%B2_16.29.39.png HTTP/1.1" 200 6052[0m basehttp.py INFO
[20/Oct/2022 11:19:47] [m"GET /media/photo/2022/10.17/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA_%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0_2022-08-16_%D0%B2_14.56.39.png HTTP/1.1" 200 282542[0m basehttp.py INFO
[20/Oct/2022 11:19:47] [m"GET /media/photo/2022/10.17/LWScreenShot_2022-09-02_at_17.30.40.png HTTP/1.1" 200 23927349[0m basehttp.py INFO
[20/Oct/2022 11:21:40,351] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[20/Oct/2022 11:21:40,850] Watching for file changes with StatReloader autoreload.py INFO
[20/Oct/2022 11:21:45] [m"GET /api/list_students/ HTTP/1.1" 200 17170[0m basehttp.py INFO
[20/Oct/2022 11:21:54,895] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[20/Oct/2022 11:21:55,952] Watching for file changes with StatReloader autoreload.py INFO
[20/Oct/2022 11:21:58] [m"GET /api/list_students/ HTTP/1.1" 200 17098[0m basehttp.py INFO
[20/Oct/2022 11:22:19,151] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[20/Oct/2022 11:22:19,615] Watching for file changes with StatReloader autoreload.py INFO
[20/Oct/2022 11:22:22,410] [35;1mInternal Server Error: /api/list_students/[0m log.py ERROR
Traceback (most recent call last):
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 507, in to_representation
    for field in fields:
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `course.name` is not valid for model `InfoStudent`.
[20/Oct/2022 11:22:22] [35;1m"GET /api/list_students/ HTTP/1.1" 500 159531[0m basehttp.py ERROR
[20/Oct/2022 11:22:32,965] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[20/Oct/2022 11:22:33,979] Watching for file changes with StatReloader autoreload.py INFO
[20/Oct/2022 11:22:40,601] [35;1mInternal Server Error: /api/list_students/[0m log.py ERROR
Traceback (most recent call last):
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 507, in to_representation
    for field in fields:
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `course_id.name` is not valid for model `InfoStudent`.
[20/Oct/2022 11:22:40] [35;1m"GET /api/list_students/ HTTP/1.1" 500 159600[0m basehttp.py ERROR
[20/Oct/2022 11:25:23,954] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[20/Oct/2022 11:25:24,909] Watching for file changes with StatReloader autoreload.py INFO
[20/Oct/2022 11:25:30,212] [33mNot Found: /favicon.ico[0m log.py WARNING
[20/Oct/2022 11:25:30] [33m"GET /favicon.ico HTTP/1.1" 404 15893[0m basehttp.py WARNING
[20/Oct/2022 11:26:37,219] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[20/Oct/2022 11:26:37,871] Watching for file changes with StatReloader autoreload.py INFO
[20/Oct/2022 11:27:03,333] [35;1mInternal Server Error: /api/list_students/[0m log.py ERROR
Traceback (most recent call last):
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 507, in to_representation
    for field in fields:
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `direction__name` is not valid for model `InfoStudent`.
[20/Oct/2022 11:27:03] [35;1m"GET /api/list_students/ HTTP/1.1" 500 160870[0m basehttp.py ERROR
[20/Oct/2022 11:29:04,479] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[20/Oct/2022 11:29:06,365] Watching for file changes with StatReloader autoreload.py INFO
[20/Oct/2022 11:30:11] [m"GET /api/list_students/ HTTP/1.1" 200 17170[0m basehttp.py INFO
[20/Oct/2022 11:33:02] [m"GET /api/list_students/ HTTP/1.1" 200 17168[0m basehttp.py INFO
[20/Oct/2022 11:43:31,167] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[20/Oct/2022 11:43:32,188] Watching for file changes with StatReloader autoreload.py INFO
[20/Oct/2022 11:43:49,384] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/views.py changed, reloading. autoreload.py INFO
[20/Oct/2022 11:43:50,591] Watching for file changes with StatReloader autoreload.py INFO
[20/Oct/2022 11:43:52,581] [33mNot Found: /api/student/[0m log.py WARNING
[20/Oct/2022 11:43:52] [33m"GET /api/student/ HTTP/1.1" 404 16177[0m basehttp.py WARNING
[20/Oct/2022 11:43:56] [m"GET /api/student/2 HTTP/1.1" 200 16605[0m basehttp.py INFO
[20/Oct/2022 12:25:18,542] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/urls.py changed, reloading. autoreload.py INFO
[20/Oct/2022 12:25:19,494] Watching for file changes with StatReloader autoreload.py INFO
[20/Oct/2022 12:27:50,650] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/views.py changed, reloading. autoreload.py INFO
[20/Oct/2022 12:27:51,643] Watching for file changes with StatReloader autoreload.py INFO
[20/Oct/2022 12:30:10,501] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/views.py changed, reloading. autoreload.py INFO
[20/Oct/2022 12:30:11,000] Watching for file changes with StatReloader autoreload.py INFO
[20/Oct/2022 12:30:23,627] [31;1mMethod Not Allowed: /api/login/[0m log.py WARNING
[20/Oct/2022 12:30:23] [31;1m"GET /api/login/ HTTP/1.1" 405 18527[0m basehttp.py WARNING
[20/Oct/2022 12:30:28] [m"POST /api/login/ HTTP/1.1" 200 18910[0m basehttp.py INFO
[20/Oct/2022 14:24:40,521] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[20/Oct/2022 14:24:41,263] Watching for file changes with StatReloader autoreload.py INFO
[20/Oct/2022 14:24:42,582] [31;1mMethod Not Allowed: /api/login/[0m log.py WARNING
[20/Oct/2022 14:24:42] [31;1m"GET /api/login/ HTTP/1.1" 405 18527[0m basehttp.py WARNING
[20/Oct/2022 14:24:46] [m"GET /api/student/2 HTTP/1.1" 200 17510[0m basehttp.py INFO
[20/Oct/2022 14:24:51] [m"GET /media/photo/2022/10.17/LWScreenShot_2022-09-02_at_17.30.40.png HTTP/1.1" 200 23927349[0m basehttp.py INFO
[20/Oct/2022 14:27:41,982] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[20/Oct/2022 14:27:42,430] Watching for file changes with StatReloader autoreload.py INFO
[20/Oct/2022 14:27:45] [m"GET /api/student/2 HTTP/1.1" 200 17540[0m basehttp.py INFO
[20/Oct/2022 14:30:59,721] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[20/Oct/2022 14:31:00,161] Watching for file changes with StatReloader autoreload.py INFO
[20/Oct/2022 14:31:03,584] [35;1mInternal Server Error: /api/student/2[0m log.py ERROR
Traceback (most recent call last):
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/fields.py", line 457, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/fields.py", line 97, in get_attribute
    instance = getattr(instance, attr)
AttributeError: 'str' object has no attribute 'get_course_display'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/generics.py", line 208, in get
    return self.retrieve(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 56, in retrieve
    return Response(serializer.data)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 509, in to_representation
    attribute = field.get_attribute(instance)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/fields.py", line 490, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `organization` on serializer `SerializerDitailStudents`.
The serializer field might be named incorrectly and not match any attribute or key on the `InfoStudent` instance.
Original exception text was: 'str' object has no attribute 'get_course_display'.
[20/Oct/2022 14:31:03] [35;1m"GET /api/student/2 HTTP/1.1" 500 141343[0m basehttp.py ERROR
[20/Oct/2022 14:32:50,268] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[20/Oct/2022 14:32:51,764] Watching for file changes with StatReloader autoreload.py INFO
[20/Oct/2022 14:32:53] [m"GET /api/student/2 HTTP/1.1" 200 17540[0m basehttp.py INFO
[20/Oct/2022 14:39:27,795] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[20/Oct/2022 14:39:28,242] Watching for file changes with StatReloader autoreload.py INFO
[20/Oct/2022 14:39:47,023] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[20/Oct/2022 14:39:47,400] Watching for file changes with StatReloader autoreload.py INFO
[20/Oct/2022 14:39:56] [m"GET /api/student/2 HTTP/1.1" 200 17540[0m basehttp.py INFO
[20/Oct/2022 14:44:39,927] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[20/Oct/2022 14:44:41,408] Watching for file changes with StatReloader autoreload.py INFO
[20/Oct/2022 14:45:00,109] Watching for file changes with StatReloader autoreload.py INFO
[20/Oct/2022 14:45:03,959] [35;1mInternal Server Error: /api/student/2[0m log.py ERROR
Traceback (most recent call last):
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/fields.py", line 457, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/fields.py", line 97, in get_attribute
    instance = getattr(instance, attr)
AttributeError: 'InfoStudent' object has no attribute 'get_destination_display'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/generics.py", line 208, in get
    return self.retrieve(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 56, in retrieve
    return Response(serializer.data)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 509, in to_representation
    attribute = field.get_attribute(instance)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/fields.py", line 490, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `course` on serializer `SerializerDitailStudents`.
The serializer field might be named incorrectly and not match any attribute or key on the `InfoStudent` instance.
Original exception text was: 'InfoStudent' object has no attribute 'get_destination_display'.
[20/Oct/2022 14:45:04] [35;1m"GET /api/student/2 HTTP/1.1" 500 140034[0m basehttp.py ERROR
[20/Oct/2022 14:46:04,378] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[20/Oct/2022 14:46:04,856] Watching for file changes with StatReloader autoreload.py INFO
[20/Oct/2022 14:46:09] [m"GET /api/student/2 HTTP/1.1" 200 17549[0m basehttp.py INFO
[20/Oct/2022 14:46:40,442] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[20/Oct/2022 14:46:40,999] Watching for file changes with StatReloader autoreload.py INFO
[20/Oct/2022 14:46:42] [m"GET /api/student/2 HTTP/1.1" 200 17569[0m basehttp.py INFO
[20/Oct/2022 14:47:52,264] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[20/Oct/2022 14:47:53,058] Watching for file changes with StatReloader autoreload.py INFO
[20/Oct/2022 14:48:06,460] [33mNot Found: /api/list_student/[0m log.py WARNING
[20/Oct/2022 14:48:06] [33m"GET /api/list_student/ HTTP/1.1" 404 16756[0m basehttp.py WARNING
[20/Oct/2022 14:48:16] [m"GET /api/list_students/ HTTP/1.1" 200 17170[0m basehttp.py INFO
[20/Oct/2022 14:48:46,052] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[20/Oct/2022 14:48:47,350] Watching for file changes with StatReloader autoreload.py INFO
[20/Oct/2022 14:48:49] [m"GET /api/student/2 HTTP/1.1" 200 16747[0m basehttp.py INFO
[20/Oct/2022 14:58:31,255] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/views.py changed, reloading. autoreload.py INFO
[20/Oct/2022 14:58:32,491] Watching for file changes with StatReloader autoreload.py INFO
[20/Oct/2022 15:05:21,183] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/views.py changed, reloading. autoreload.py INFO
[20/Oct/2022 15:05:21,592] Watching for file changes with StatReloader autoreload.py INFO
[20/Oct/2022 15:05:26,004] [35;1mInternal Server Error: /api/student/2[0m log.py ERROR
Traceback (most recent call last):
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/generics.py", line 208, in get
    return self.retrieve(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 56, in retrieve
    return Response(serializer.data)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 507, in to_representation
    for field in fields:
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `a` is not valid for model `InfoStudent`.
[20/Oct/2022 15:05:26] [35;1m"GET /api/student/2 HTTP/1.1" 500 151700[0m basehttp.py ERROR
[20/Oct/2022 15:05:39,600] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[20/Oct/2022 15:05:40,116] Watching for file changes with StatReloader autoreload.py INFO
[20/Oct/2022 15:08:52,984] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/views.py changed, reloading. autoreload.py INFO
[20/Oct/2022 15:08:54,127] Watching for file changes with StatReloader autoreload.py INFO
[20/Oct/2022 15:09:17,255] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/views.py changed, reloading. autoreload.py INFO
[20/Oct/2022 15:09:18,001] Watching for file changes with StatReloader autoreload.py INFO
[20/Oct/2022 15:09:55,547] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/views.py changed, reloading. autoreload.py INFO
[20/Oct/2022 15:09:56,304] Watching for file changes with StatReloader autoreload.py INFO
[20/Oct/2022 15:10:03] [m"GET /api/student/2 HTTP/1.1" 200 16747[0m basehttp.py INFO
[20/Oct/2022 15:10:27,669] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/views.py changed, reloading. autoreload.py INFO
[20/Oct/2022 15:10:28,122] Watching for file changes with StatReloader autoreload.py INFO
[20/Oct/2022 15:10:31] [m"GET /api/student/2 HTTP/1.1" 200 16747[0m basehttp.py INFO
[20/Oct/2022 15:20:21] [m"GET /admin/ HTTP/1.1" 200 19819[0m basehttp.py INFO
[20/Oct/2022 15:20:24] [m"GET /admin/Students/events/ HTTP/1.1" 200 21320[0m basehttp.py INFO
[20/Oct/2022 15:20:24] [m"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 232381[0m basehttp.py INFO
[20/Oct/2022 15:20:24] [m"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 288580[0m basehttp.py INFO
[20/Oct/2022 15:20:24] [m"GET /admin/jsi18n/ HTTP/1.1" 200 15618[0m basehttp.py INFO
[20/Oct/2022 15:21:26,450] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Students/admin.py changed, reloading. autoreload.py INFO
[20/Oct/2022 15:21:27,017] Watching for file changes with StatReloader autoreload.py INFO
[20/Oct/2022 15:22:00,485] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Students/admin.py changed, reloading. autoreload.py INFO
[20/Oct/2022 15:22:01,184] Watching for file changes with StatReloader autoreload.py INFO
[20/Oct/2022 15:22:42,453] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Students/admin.py changed, reloading. autoreload.py INFO
[20/Oct/2022 15:22:42,910] Watching for file changes with StatReloader autoreload.py INFO
[20/Oct/2022 15:23:12,880] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Students/admin.py changed, reloading. autoreload.py INFO
[20/Oct/2022 15:23:13,506] Watching for file changes with StatReloader autoreload.py INFO
[20/Oct/2022 15:24:18,367] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Students/admin.py changed, reloading. autoreload.py INFO
[20/Oct/2022 15:24:19,146] Watching for file changes with StatReloader autoreload.py INFO
[20/Oct/2022 15:24:45,769] [35;1mInternal Server Error: /admin/Students/events/[0m log.py ERROR
Traceback (most recent call last):
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/db/models/options.py", line 608, in get_field
    return self.fields_map[field_name]
KeyError: 'view_students_link'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/contrib/admin/utils.py", line 266, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/contrib/admin/utils.py", line 297, in _get_non_gfk_field
    field = opts.get_field(name)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/db/models/options.py", line 610, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: Events has no field named 'view_students_link'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/template/base.py", line 176, in render
    return self._render(context)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/test/utils.py", line 101, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/template/base.py", line 977, in render
    return SafeString(''.join([
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/template/base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/template/base.py", line 938, in render_annotated
    return self.render(context)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 153, in render
    return compiled_parent._render(context)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/test/utils.py", line 101, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/template/base.py", line 977, in render
    return SafeString(''.join([
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/template/base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/template/base.py", line 938, in render_annotated
    return self.render(context)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 153, in render
    return compiled_parent._render(context)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/test/utils.py", line 101, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/template/base.py", line 977, in render
    return SafeString(''.join([
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/template/base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/template/base.py", line 938, in render_annotated
    return self.render(context)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/template/base.py", line 977, in render
    return SafeString(''.join([
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/template/base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/template/base.py", line 938, in render_annotated
    return self.render(context)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/template/base.py", line 977, in render
    return SafeString(''.join([
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/template/base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/template/base.py", line 938, in render_annotated
    return self.render(context)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/contrib/admin/templatetags/base.py", line 33, in render
    return super().render(context)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/template/library.py", line 215, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/contrib/admin/templatetags/admin_list.py", line 309, in result_list
    'results': list(results(cl)),
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/contrib/admin/templatetags/admin_list.py", line 285, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/contrib/admin/templatetags/admin_list.py", line 276, in __init__
    super().__init__(*items)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/contrib/admin/templatetags/admin_list.py", line 201, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/contrib/admin/utils.py", line 275, in lookup_field
    value = attr(obj)
  File "/Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Students/admin.py", line 56, in view_students_link
    count = obj.customuser_set.count()
AttributeError: 'Events' object has no attribute 'customuser_set'
[20/Oct/2022 15:24:45] [35;1m"GET /admin/Students/events/ HTTP/1.1" 500 409093[0m basehttp.py ERROR
[20/Oct/2022 15:25:26] [m"GET /admin/ HTTP/1.1" 200 19819[0m basehttp.py INFO
[20/Oct/2022 15:25:37,681] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Students/admin.py changed, reloading. autoreload.py INFO
[20/Oct/2022 15:25:38,730] Watching for file changes with StatReloader autoreload.py INFO
[20/Oct/2022 15:26:10,880] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Students/admin.py changed, reloading. autoreload.py INFO
[20/Oct/2022 15:26:11,942] Watching for file changes with StatReloader autoreload.py INFO
[20/Oct/2022 15:28:05,385] Watching for file changes with StatReloader autoreload.py INFO
[20/Oct/2022 15:28:13,835] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Students/admin.py changed, reloading. autoreload.py INFO
[20/Oct/2022 15:28:14,304] Watching for file changes with StatReloader autoreload.py INFO
[20/Oct/2022 15:28:16] [m"GET /admin/auth/group/ HTTP/1.1" 200 18099[0m basehttp.py INFO
[20/Oct/2022 15:28:17] [m"GET /admin/jsi18n/ HTTP/1.1" 200 15618[0m basehttp.py INFO
[20/Oct/2022 15:28:17] [m"GET /static/admin/img/search.svg HTTP/1.1" 200 458[0m basehttp.py INFO
[20/Oct/2022 15:28:19] [m"GET /admin/auth/group/add/ HTTP/1.1" 200 23279[0m basehttp.py INFO
[20/Oct/2022 15:28:19] [m"GET /static/admin/css/forms.css HTTP/1.1" 200 8835[0m basehttp.py INFO
[20/Oct/2022 15:28:19] [m"GET /static/admin/js/SelectBox.js HTTP/1.1" 200 4360[0m basehttp.py INFO
[20/Oct/2022 15:28:19] [m"GET /static/admin/js/SelectFilter2.js HTTP/1.1" 200 12350[0m basehttp.py INFO
[20/Oct/2022 15:28:19] [m"GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 492[0m basehttp.py INFO
[20/Oct/2022 15:28:19] [m"GET /static/admin/css/widgets.css HTTP/1.1" 200 11097[0m basehttp.py INFO
[20/Oct/2022 15:28:20] [m"GET /static/admin/js/change_form.js HTTP/1.1" 200 606[0m basehttp.py INFO
[20/Oct/2022 15:28:20] [m"GET /admin/jsi18n/ HTTP/1.1" 200 15618[0m basehttp.py INFO
[20/Oct/2022 15:28:20] [m"GET /static/admin/img/icon-unknown.svg HTTP/1.1" 200 655[0m basehttp.py INFO
[20/Oct/2022 15:28:20] [m"GET /static/admin/img/selector-icons.svg HTTP/1.1" 200 3291[0m basehttp.py INFO
[20/Oct/2022 15:28:20] [m"GET /static/admin/img/icon-unknown-alt.svg HTTP/1.1" 200 655[0m basehttp.py INFO
[21/Oct/2022 10:01:12,552] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/views.py changed, reloading. autoreload.py INFO
[21/Oct/2022 10:01:13,728] Watching for file changes with StatReloader autoreload.py INFO
[21/Oct/2022 10:01:18] [m"GET /api/student/2 HTTP/1.1" 200 16747[0m basehttp.py INFO
[21/Oct/2022 10:01:18] [36m"GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0[0m basehttp.py INFO
[21/Oct/2022 10:01:18] [36m"GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0[0m basehttp.py INFO
[21/Oct/2022 10:01:18] [36m"GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0[0m basehttp.py INFO
[21/Oct/2022 10:01:18] [36m"GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0[0m basehttp.py INFO
[21/Oct/2022 10:01:18] [36m"GET /static/rest_framework/css/default.css HTTP/1.1" 304 0[0m basehttp.py INFO
[21/Oct/2022 10:01:18] [m"GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385[0m basehttp.py INFO
[21/Oct/2022 10:01:18] [36m"GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0[0m basehttp.py INFO
[21/Oct/2022 10:01:18] [36m"GET /static/rest_framework/js/default.js HTTP/1.1" 304 0[0m basehttp.py INFO
[21/Oct/2022 10:01:18] [36m"GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0[0m basehttp.py INFO
[21/Oct/2022 10:01:18] [m"GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 200 11815[0m basehttp.py INFO
[21/Oct/2022 10:01:18] [m"GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 200 12222[0m basehttp.py INFO
[21/Oct/2022 10:01:18] [m"GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457[0m basehttp.py INFO
[21/Oct/2022 10:01:18] [36m"GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0[0m basehttp.py INFO
[21/Oct/2022 10:01:18] [m"GET /static/debug_toolbar/js/utils.js HTTP/1.1" 200 4479[0m basehttp.py INFO
[21/Oct/2022 10:01:38,452] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/views.py changed, reloading. autoreload.py INFO
[21/Oct/2022 10:01:39,041] Watching for file changes with StatReloader autoreload.py INFO
[21/Oct/2022 10:01:40] [m"GET /api/student/2 HTTP/1.1" 200 16747[0m basehttp.py INFO
[21/Oct/2022 10:01:44] [m"GET /api/student/2 HTTP/1.1" 200 16745[0m basehttp.py INFO
[21/Oct/2022 10:01:56,159] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/views.py changed, reloading. autoreload.py INFO
[21/Oct/2022 10:01:56,670] Watching for file changes with StatReloader autoreload.py INFO
[21/Oct/2022 10:01:59] [m"GET /api/student/2 HTTP/1.1" 200 16747[0m basehttp.py INFO
[21/Oct/2022 10:18:28,553] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/views.py changed, reloading. autoreload.py INFO
[21/Oct/2022 10:18:30,494] Watching for file changes with StatReloader autoreload.py INFO
[21/Oct/2022 10:18:31] [m"GET /api/student/2 HTTP/1.1" 200 16747[0m basehttp.py INFO
[21/Oct/2022 10:18:36] [m"GET /api/student/2?format=json HTTP/1.1" 200 157[0m basehttp.py INFO
[21/Oct/2022 10:18:41] [m"GET /api/student/2 HTTP/1.1" 200 16745[0m basehttp.py INFO
[21/Oct/2022 10:22:47,200] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/views.py changed, reloading. autoreload.py INFO
[21/Oct/2022 10:22:48,803] Watching for file changes with StatReloader autoreload.py INFO
[21/Oct/2022 10:23:06,125] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/views.py changed, reloading. autoreload.py INFO
[21/Oct/2022 10:23:06,655] Watching for file changes with StatReloader autoreload.py INFO
[21/Oct/2022 10:23:11] [m"GET /api/student/2 HTTP/1.1" 200 16747[0m basehttp.py INFO
[21/Oct/2022 10:24:09,811] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/views.py changed, reloading. autoreload.py INFO
[21/Oct/2022 10:24:11,034] Watching for file changes with StatReloader autoreload.py INFO
[21/Oct/2022 10:24:22] [m"GET /api/list_students/ HTTP/1.1" 200 17206[0m basehttp.py INFO
[21/Oct/2022 10:27:14,115] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/views.py changed, reloading. autoreload.py INFO
[21/Oct/2022 10:27:15,928] Watching for file changes with StatReloader autoreload.py INFO
[21/Oct/2022 10:28:25,032] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/views.py changed, reloading. autoreload.py INFO
[21/Oct/2022 10:28:25,822] Watching for file changes with StatReloader autoreload.py INFO
[21/Oct/2022 12:21:42,377] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[21/Oct/2022 12:21:43,526] Watching for file changes with StatReloader autoreload.py INFO
[21/Oct/2022 12:22:04,420] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[21/Oct/2022 12:22:04,991] Watching for file changes with StatReloader autoreload.py INFO
[21/Oct/2022 12:22:13,948] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[21/Oct/2022 12:22:14,540] Watching for file changes with StatReloader autoreload.py INFO
[21/Oct/2022 12:22:33,820] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[21/Oct/2022 12:22:34,517] Watching for file changes with StatReloader autoreload.py INFO
[21/Oct/2022 12:22:48,636] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[21/Oct/2022 12:22:49,549] Watching for file changes with StatReloader autoreload.py INFO
[21/Oct/2022 12:23:09,470] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[21/Oct/2022 12:23:10,687] Watching for file changes with StatReloader autoreload.py INFO
[21/Oct/2022 12:23:15,882] [35;1mInternal Server Error: /api/list_students/[0m log.py ERROR
Traceback (most recent call last):
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 507, in to_representation
    for field in fields:
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 1052, in get_fields
    field_names = self.get_field_names(declared_fields, info)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 1148, in get_field_names
    assert field_name in fields, (
AssertionError: The field 'assda' was declared on serializer SerializerListStudents, but has not been included in the 'fields' option.
[21/Oct/2022 12:23:15] [35;1m"GET /api/list_students/ HTTP/1.1" 500 156287[0m basehttp.py ERROR
[21/Oct/2022 12:23:31,331] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[21/Oct/2022 12:23:32,598] Watching for file changes with StatReloader autoreload.py INFO
[21/Oct/2022 12:23:50,527] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[21/Oct/2022 12:23:51,657] Watching for file changes with StatReloader autoreload.py INFO
[21/Oct/2022 12:23:59,247] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[21/Oct/2022 12:23:59,796] Watching for file changes with StatReloader autoreload.py INFO
[21/Oct/2022 12:51:48,256] [33mNot Found: /[0m log.py WARNING
[21/Oct/2022 12:51:48] [33m"GET / HTTP/1.1" 404 15831[0m basehttp.py WARNING
[21/Oct/2022 12:51:59,402] [31;1mUnauthorized: /api/list_students/[0m log.py WARNING
[21/Oct/2022 12:51:59] [31;1m"GET /api/list_students/ HTTP/1.1" 401 16191[0m basehttp.py WARNING
[21/Oct/2022 12:51:59] [m"GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632[0m basehttp.py INFO
[21/Oct/2022 12:51:59] [m"GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597[0m basehttp.py INFO
[21/Oct/2022 12:51:59] [m"GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680[0m basehttp.py INFO
[21/Oct/2022 12:51:59] [m"GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 200 89476[0m basehttp.py INFO
[21/Oct/2022 12:51:59] [m"GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457[0m basehttp.py INFO
[21/Oct/2022 12:52:24,241] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/views.py changed, reloading. autoreload.py INFO
[21/Oct/2022 12:52:25,590] Watching for file changes with StatReloader autoreload.py INFO
[21/Oct/2022 12:52:27,542] [35;1mInternal Server Error: /api/list_students/[0m log.py ERROR
Traceback (most recent call last):
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 507, in to_representation
    for field in fields:
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 1052, in get_fields
    field_names = self.get_field_names(declared_fields, info)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 1148, in get_field_names
    assert field_name in fields, (
AssertionError: The field 'days_since_joined' was declared on serializer SerializerListStudents, but has not been included in the 'fields' option.
[21/Oct/2022 12:52:27] [35;1m"GET /api/list_students/ HTTP/1.1" 500 156326[0m basehttp.py ERROR
[21/Oct/2022 12:53:03,321] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[21/Oct/2022 12:53:04,406] Watching for file changes with StatReloader autoreload.py INFO
[21/Oct/2022 12:53:10,620] [35;1mInternal Server Error: /api/list_students/[0m log.py ERROR
Traceback (most recent call last):
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/fields.py", line 1886, in to_representation
    return method(value)
  File "/Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py", line 19, in get_days_since_joined
    return (now() - obj.date_joined).days
AttributeError: 'InfoStudent' object has no attribute 'date_joined'
[21/Oct/2022 12:53:10] [35;1m"GET /api/list_students/ HTTP/1.1" 500 136932[0m basehttp.py ERROR
[21/Oct/2022 12:53:37,457] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[21/Oct/2022 12:53:38,335] Watching for file changes with StatReloader autoreload.py INFO
[21/Oct/2022 12:53:41] [m"GET /api/list_students/ HTTP/1.1" 200 17146[0m basehttp.py INFO
[21/Oct/2022 12:53:54,602] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[21/Oct/2022 12:53:55,470] Watching for file changes with StatReloader autoreload.py INFO
[21/Oct/2022 12:53:58] [m"GET /api/list_students/ HTTP/1.1" 200 17210[0m basehttp.py INFO
[21/Oct/2022 12:54:37,537] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[21/Oct/2022 12:54:38,836] Watching for file changes with StatReloader autoreload.py INFO
[21/Oct/2022 12:54:40,497] [35;1mInternal Server Error: /api/list_students/[0m log.py ERROR
Traceback (most recent call last):
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 507, in to_representation
    for field in fields:
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `get_days` is not valid for model `InfoStudent`.
[21/Oct/2022 12:54:40] [35;1m"GET /api/list_students/ HTTP/1.1" 500 159594[0m basehttp.py ERROR
[21/Oct/2022 12:54:56,127] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[21/Oct/2022 12:54:57,233] Watching for file changes with StatReloader autoreload.py INFO
[21/Oct/2022 12:57:38,221] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[21/Oct/2022 12:57:38,639] Watching for file changes with StatReloader autoreload.py INFO
[21/Oct/2022 12:57:42] [m"GET /api/list_students/ HTTP/1.1" 200 17158[0m basehttp.py INFO
[21/Oct/2022 12:58:37,088] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[21/Oct/2022 12:58:37,806] Watching for file changes with StatReloader autoreload.py INFO
[21/Oct/2022 12:58:40,940] [35;1mInternal Server Error: /api/list_students/[0m log.py ERROR
Traceback (most recent call last):
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/fields.py", line 1886, in to_representation
    return method(value)
  File "/Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py", line 19, in get_days
    return obj.count()
AttributeError: 'InfoStudent' object has no attribute 'count'
[21/Oct/2022 12:58:41] [35;1m"GET /api/list_students/ HTTP/1.1" 500 136663[0m basehttp.py ERROR
[21/Oct/2022 13:01:15,336] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[21/Oct/2022 13:01:15,817] Watching for file changes with StatReloader autoreload.py INFO
[21/Oct/2022 13:01:20,768] [35;1mInternal Server Error: /api/list_students/[0m log.py ERROR
Traceback (most recent call last):
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/fields.py", line 1886, in to_representation
    return method(value)
  File "/Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py", line 19, in get_days
    return obj.objects.count()
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 179, in __get__
    raise AttributeError("Manager isn't accessible via %s instances" % cls.__name__)
AttributeError: Manager isn't accessible via InfoStudent instances
[21/Oct/2022 13:01:20] [35;1m"GET /api/list_students/ HTTP/1.1" 500 140598[0m basehttp.py ERROR
[21/Oct/2022 13:26:46,194] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[21/Oct/2022 13:26:46,689] Watching for file changes with StatReloader autoreload.py INFO
[21/Oct/2022 13:26:49] [m"GET /api/list_students/ HTTP/1.1" 200 17150[0m basehttp.py INFO
[21/Oct/2022 13:28:40,662] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/views.py changed, reloading. autoreload.py INFO
[21/Oct/2022 13:28:42,030] Watching for file changes with StatReloader autoreload.py INFO
[21/Oct/2022 13:28:43,400] [35;1mInternal Server Error: /api/test/[0m log.py ERROR
Traceback (most recent call last):
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: test.get() takes 1 positional argument but 2 were given
[21/Oct/2022 13:28:43] [35;1m"GET /api/test/ HTTP/1.1" 500 96294[0m basehttp.py ERROR
[21/Oct/2022 13:39:55,929] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Students/views.py changed, reloading. autoreload.py INFO
[21/Oct/2022 13:39:56,570] Watching for file changes with StatReloader autoreload.py INFO
[21/Oct/2022 13:40:04,945] [33mNot Found: //[0m log.py WARNING
[21/Oct/2022 13:40:04] [33m"GET // HTTP/1.1" 404 16020[0m basehttp.py WARNING
[21/Oct/2022 13:40:11] [m"GET /test/ HTTP/1.1" 200 12966[0m basehttp.py INFO
[21/Oct/2022 13:40:11] [36m"GET /static/icon/logo.png HTTP/1.1" 304 0[0m basehttp.py INFO
[21/Oct/2022 13:40:11] [m"GET /static/css/style.css HTTP/1.1" 200 1895[0m basehttp.py INFO
[21/Oct/2022 13:42:12,488] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Students/urls.py changed, reloading. autoreload.py INFO
[21/Oct/2022 13:42:12,959] Watching for file changes with StatReloader autoreload.py INFO
[21/Oct/2022 13:42:44,110] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/views.py changed, reloading. autoreload.py INFO
[21/Oct/2022 13:42:45,283] Watching for file changes with StatReloader autoreload.py INFO
[21/Oct/2022 13:56:13,309] [33mNot Found: /test/[0m log.py WARNING
[21/Oct/2022 13:56:13] [33m"GET /test/ HTTP/1.1" 404 15869[0m basehttp.py WARNING
[21/Oct/2022 13:56:18] [32m"GET /list_students/ HTTP/1.1" 302 0[0m basehttp.py INFO
[21/Oct/2022 13:56:18] [m"GET /login/?next=/list_students/ HTTP/1.1" 200 13805[0m basehttp.py INFO
[21/Oct/2022 13:56:18] [m"GET /static/icon/logo.png HTTP/1.1" 200 513410[0m basehttp.py INFO
[21/Oct/2022 13:56:36] [32m"POST /login/ HTTP/1.1" 302 0[0m basehttp.py INFO
[21/Oct/2022 13:56:36,485] [35;1mInternal Server Error: /api/test/[0m log.py ERROR
Traceback (most recent call last):
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: test.get() takes 1 positional argument but 2 were given
[21/Oct/2022 13:56:36] [35;1m"GET /api/test/ HTTP/1.1" 500 96818[0m basehttp.py ERROR
[21/Oct/2022 13:56:46] [m"GET /list_students/ HTTP/1.1" 200 16970[0m basehttp.py INFO
[21/Oct/2022 13:56:47] [m"GET /media/photo/2022/10.17/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA_%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0_2022-08-16_%D0%B2_14.56.56.png HTTP/1.1" 200 288574[0m basehttp.py INFO
[21/Oct/2022 13:56:47] [m"GET /media/photo/2022/10.17/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA_%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0_2022-08-12_%D0%B2_16.29.39.png HTTP/1.1" 200 6052[0m basehttp.py INFO
[21/Oct/2022 13:56:47] [m"GET /media/photo/2022/10.17/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA_%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0_2022-08-16_%D0%B2_14.56.39.png HTTP/1.1" 200 282542[0m basehttp.py INFO
[21/Oct/2022 13:56:47] [m"GET /media/photo/2022/10.17/LWScreenShot_2022-09-02_at_17.30.40.png HTTP/1.1" 200 23927349[0m basehttp.py INFO
[21/Oct/2022 14:08:17] [m"GET /api/list_students/ HTTP/1.1" 200 17378[0m basehttp.py INFO
[21/Oct/2022 14:08:40,269] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[21/Oct/2022 14:08:40,980] Watching for file changes with StatReloader autoreload.py INFO
[21/Oct/2022 14:08:44,397] [35;1mInternal Server Error: /api/list_students/[0m log.py ERROR
Traceback (most recent call last):
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 507, in to_representation
    for field in fields:
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 1052, in get_fields
    field_names = self.get_field_names(declared_fields, info)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 1148, in get_field_names
    assert field_name in fields, (
AssertionError: The field 'course' was declared on serializer SerializerListStudents, but has not been included in the 'fields' option.
[21/Oct/2022 14:08:44] [35;1m"GET /api/list_students/ HTTP/1.1" 500 156148[0m basehttp.py ERROR
[21/Oct/2022 14:08:52,837] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[21/Oct/2022 14:08:53,872] Watching for file changes with StatReloader autoreload.py INFO
[21/Oct/2022 14:08:55] [m"GET /api/list_students/ HTTP/1.1" 200 16998[0m basehttp.py INFO
[21/Oct/2022 14:21:25,013] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[21/Oct/2022 14:21:26,517] Watching for file changes with StatReloader autoreload.py INFO
[21/Oct/2022 14:24:28,557] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[21/Oct/2022 14:24:30,322] Watching for file changes with StatReloader autoreload.py INFO
[21/Oct/2022 14:24:32] [m"GET /api/list_students/ HTTP/1.1" 200 17226[0m basehttp.py INFO
[21/Oct/2022 14:29:59,233] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[21/Oct/2022 14:30:00,702] Watching for file changes with StatReloader autoreload.py INFO
[21/Oct/2022 14:32:11,803] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/serializers.py changed, reloading. autoreload.py INFO
[21/Oct/2022 14:32:12,906] Watching for file changes with StatReloader autoreload.py INFO
[21/Oct/2022 14:33:11,088] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/views.py changed, reloading. autoreload.py INFO
[21/Oct/2022 14:33:12,088] Watching for file changes with StatReloader autoreload.py INFO
[21/Oct/2022 14:33:22,826] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/views.py changed, reloading. autoreload.py INFO
[21/Oct/2022 14:33:23,372] Watching for file changes with StatReloader autoreload.py INFO
[21/Oct/2022 14:33:30,231] [35;1mInternal Server Error: /api/list_students/[0m log.py ERROR
Traceback (most recent call last):
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/generics.py", line 178, in get_paginated_response
    return self.paginator.get_paginated_response(data)
  File "/Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/views.py", line 43, in get_paginated_response
    prices = [dict(item)['average_price'] for item in data]
  File "/Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/views.py", line 43, in <listcomp>
    prices = [dict(item)['average_price'] for item in data]
KeyError: 'average_price'
[21/Oct/2022 14:33:30] [35;1m"GET /api/list_students/ HTTP/1.1" 500 118729[0m basehttp.py ERROR
[21/Oct/2022 14:33:41,394] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/views.py changed, reloading. autoreload.py INFO
[21/Oct/2022 14:33:41,987] Watching for file changes with StatReloader autoreload.py INFO
[21/Oct/2022 14:33:44] [m"GET /api/list_students/ HTTP/1.1" 200 17507[0m basehttp.py INFO
[21/Oct/2022 14:34:09,625] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/views.py changed, reloading. autoreload.py INFO
[21/Oct/2022 14:34:10,268] Watching for file changes with StatReloader autoreload.py INFO
[21/Oct/2022 14:34:12,721] [35;1mInternal Server Error: /api/list_students/[0m log.py ERROR
Traceback (most recent call last):
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
  File "/Users/radix-dev/PycharmProjects/dgu/venv/lib/python3.10/site-packages/rest_framework/generics.py", line 178, in get_paginated_response
    return self.paginator.get_paginated_response(data)
  File "/Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/views.py", line 45, in get_paginated_response
    'result': data.count(),
TypeError: list.count() takes exactly one argument (0 given)
[21/Oct/2022 14:34:13] [35;1m"GET /api/list_students/ HTTP/1.1" 500 115163[0m basehttp.py ERROR
[21/Oct/2022 14:34:31,494] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/views.py changed, reloading. autoreload.py INFO
[21/Oct/2022 14:34:32,057] Watching for file changes with StatReloader autoreload.py INFO
[21/Oct/2022 14:34:36] [m"GET /api/list_students/ HTTP/1.1" 200 17534[0m basehttp.py INFO
[21/Oct/2022 14:38:02,818] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/views.py changed, reloading. autoreload.py INFO
[21/Oct/2022 14:38:03,296] Watching for file changes with StatReloader autoreload.py INFO
[21/Oct/2022 14:38:07] [m"GET /api/list_students/ HTTP/1.1" 200 17560[0m basehttp.py INFO
[21/Oct/2022 14:40:39,870] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/Api/views.py changed, reloading. autoreload.py INFO
[21/Oct/2022 14:40:40,801] Watching for file changes with StatReloader autoreload.py INFO
[21/Oct/2022 14:43:33,678] /Users/radix-dev/PycharmProjects/dgu/MainPartSiteDGU/MainPartSiteDGU/settings.py changed, reloading. autoreload.py INFO
[21/Oct/2022 14:44:23,764] Watching for file changes with StatReloader autoreload.py INFO
